/**
 * Default Invoice Template
 * Simple, clean template for basic invoicing needs
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'default_invoice',
    name: 'Default Invoice',
    description: 'Simple, clean template for basic invoicing needs',
    version: '1.0.0',
    premium: false,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: {
      top: 40,
      left: 40,
      right: 40,
      bottom: 40,
    },
    background: null,
  },
  elements: [
    {
      id: 'title_1',
      type: 'text',
      x: 40,
      y: 40,
      width: 300,
      height: 40,
      content: 'FAKTURA',
      fontFamily: 'Inter',
      fontSize: 28,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'field_number',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 40,
      y: 100,
      width: 200,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'field_date',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 40,
      y: 130,
      width: 200,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 40,
      y: 200,
      width: 500,
      height: 300,
      columns: [
        { header: 'Beskrivelse', field: 'description', width: 250, align: 'left' },
        { header: 'Antall', field: 'quantity', width: 50, align: 'right' },
        { header: 'Pris', field: 'unit_price', width: 80, align: 'right' },
        { header: 'MVA', field: 'vat_rate', width: 50, align: 'right' },
        { header: 'Total', field: 'line_total', width: 80, align: 'right' },
      ],
      rowHeight: 18,
      maxRows: 15,
    },
  ],
};

