/**
 * Classic Elite Premium Template
 * Traditional but refined, with professional styling, perfect spacing, and timeless elegance
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'premium_classic_elite',
    name: 'Classic Elite',
    description: 'Traditional but refined, with professional styling, perfect spacing, and timeless elegance',
    version: '1.0.0',
    premium: true,
    tags: ['classic', 'traditional', 'premium', 'norsk'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: {
      top: 55,
      left: 65,
      right: 65,
      bottom: 55,
    },
    background: null,
  },
  elements: [
    // Classic header box
    {
      id: 'header_box',
      type: 'shape',
      shapeType: 'rectangle',
      x: 65,
      y: 55,
      width: 624,
      height: 130,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      borderRadius: 0,
      zIndex: 0,
    },
    // Title in header
    {
      id: 'title',
      type: 'text',
      x: 85,
      y: 75,
      width: 350,
      height: 45,
      content: 'INVOICE',
      fontFamily: 'Inter',
      fontSize: 44,
      fontWeight: 700,
      color: '#ffffff',
      align: 'left',
      letterSpacing: 3,
    },
    // Invoice details in header
    {
      id: 'invoice_number_label',
      type: 'text',
      x: 85,
      y: 130,
      width: 140,
      height: 12,
      content: 'Invoice No.',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 500,
      color: '#ffffff',
      align: 'left',
      opacity: 0.85,
      letterSpacing: 0.8,
    },
    {
      id: 'invoice_number',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 235,
      y: 128,
      width: 200,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 600,
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'invoice_date_label',
      type: 'text',
      x: 85,
      y: 155,
      width: 140,
      height: 12,
      content: 'Date',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 500,
      color: '#ffffff',
      align: 'left',
      opacity: 0.85,
      letterSpacing: 0.8,
    },
    {
      id: 'invoice_date',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 235,
      y: 153,
      width: 200,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 400,
      color: '#ffffff',
      align: 'left',
    },
    // Company info in header
    {
      id: 'company_name',
      type: 'field',
      binding: 'company.name',
      x: 449,
      y: 75,
      width: 240,
      height: 22,
      fontFamily: 'Inter',
      fontSize: 15,
      fontWeight: 700,
      color: '#ffffff',
      align: 'right',
    },
    {
      id: 'company_address',
      type: 'field',
      binding: 'company.address',
      x: 449,
      y: 103,
      width: 240,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#ffffff',
      align: 'right',
      opacity: 0.9,
    },
    {
      id: 'company_post',
      type: 'text',
      x: 449,
      y: 125,
      width: 240,
      height: 18,
      content: '',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#ffffff',
      align: 'right',
      opacity: 0.9,
    },
    {
      id: 'company_org',
      type: 'field',
      binding: 'company.org_number',
      x: 449,
      y: 147,
      width: 240,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#ffffff',
      align: 'right',
      opacity: 0.9,
    },
    {
      id: 'company_account',
      type: 'field',
      binding: 'company.account_number',
      x: 449,
      y: 169,
      width: 240,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 600,
      color: '#ffffff',
      align: 'right',
    },
    // Bill To section
    {
      id: 'bill_to_label',
      type: 'text',
      x: 65,
      y: 220,
      width: 200,
      height: 14,
      content: 'Bill To',
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 700,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
    },
    {
      id: 'customer_name',
      type: 'field',
      binding: 'customer.name',
      x: 65,
      y: 245,
      width: 350,
      height: 24,
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'customer_address',
      type: 'field',
      binding: 'customer.address',
      x: 65,
      y: 275,
      width: 350,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'customer_post',
      type: 'text',
      x: 65,
      y: 297,
      width: 350,
      height: 18,
      content: '',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    // Professional table
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 65,
      y: 340,
      width: 624,
      height: 400,
      columns: [
        { header: 'Description', field: 'description', width: 320, align: 'left' },
        { header: 'Quantity', field: 'quantity', width: 80, align: 'right' },
        { header: 'Unit Price', field: 'unit_price', width: 110, align: 'right' },
        { header: 'VAT', field: 'vat_rate', width: 60, align: 'right' },
        { header: 'Amount', field: 'line_total', width: 110, align: 'right' },
      ],
      rowHeight: 28,
      maxRows: 12,
      headerBackgroundColor: '#0d3e51',
      headerTextColor: '#ffffff',
      headerFontSize: 10,
      headerFontWeight: 700,
      headerTextTransform: 'uppercase',
      headerLetterSpacing: 1,
      backgroundColor: '#ffffff',
      rowTextColor: '#0d3e51',
      borderRadius: 0,
      borderColor: '#d5e7e6',
      borderWidth: 1,
      alternateRowColor: '#f8faf9',
    },
    // Summary box with professional styling
    {
      id: 'summary_box',
      type: 'shape',
      shapeType: 'rectangle',
      x: 429,
      y: 760,
      width: 260,
      height: 150,
      backgroundColor: '#f0f8f5',
      borderWidth: 1,
      borderColor: '#d5e7e6',
      borderRadius: 0,
      zIndex: 0,
    },
    {
      id: 'subtotal_label',
      type: 'text',
      x: 439,
      y: 780,
      width: 160,
      height: 20,
      content: 'Subtotal',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'subtotal',
      type: 'field',
      binding: 'invoice.subtotal',
      x: 599,
      y: 780,
      width: 80,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'vat_label',
      type: 'text',
      x: 439,
      y: 810,
      width: 160,
      height: 20,
      content: 'VAT',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'vat_total',
      type: 'field',
      binding: 'invoice.vat_total',
      x: 599,
      y: 810,
      width: 80,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'divider',
      type: 'shape',
      shapeType: 'rectangle',
      x: 439,
      y: 845,
      width: 240,
      height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0,
      zIndex: 1,
    },
    {
      id: 'total_label',
      type: 'text',
      x: 439,
      y: 860,
      width: 160,
      height: 28,
      content: 'Total',
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: 800,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.5,
    },
    {
      id: 'total',
      type: 'field',
      binding: 'invoice.total',
      x: 599,
      y: 860,
      width: 80,
      height: 28,
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: 800,
      color: '#0d3e51',
      align: 'right',
    },
  ],
};

