/**
 * Luxury Premium Template
 * Ultra-refined design with sophisticated typography, generous whitespace, and elegant details
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'premium_luxury',
    name: 'Luxury',
    description: 'Ultra-refined design with sophisticated typography, generous whitespace, and elegant details',
    version: '1.0.0',
    premium: true,
    tags: ['luxury', 'elegant', 'premium', 'norsk'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: {
      top: 70,
      left: 80,
      right: 80,
      bottom: 70,
    },
    background: null,
  },
  elements: [
    // Elegant top accent bar
    {
      id: 'top_accent',
      type: 'shape',
      shapeType: 'rectangle',
      x: 80,
      y: 70,
      width: 554,
      height: 6,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      borderRadius: 0,
      zIndex: 0,
    },
    // Invoice title - ultra-light, large, elegant
    {
      id: 'title',
      type: 'text',
      x: 80,
      y: 95,
      width: 400,
      height: 60,
      content: 'INVOICE',
      fontFamily: 'Inter',
      fontSize: 56,
      fontWeight: 100,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 12,
    },
    // Invoice details - refined typography
    {
      id: 'invoice_number_label',
      type: 'text',
      x: 80,
      y: 175,
      width: 180,
      height: 11,
      content: 'Invoice Number',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    {
      id: 'invoice_number',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 80,
      y: 192,
      width: 250,
      height: 22,
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.5,
    },
    {
      id: 'invoice_date_label',
      type: 'text',
      x: 80,
      y: 230,
      width: 180,
      height: 11,
      content: 'Date Issued',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    {
      id: 'invoice_date',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 80,
      y: 247,
      width: 250,
      height: 22,
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'left',
    },
    // Company info - elegant right alignment
    {
      id: 'company_name',
      type: 'field',
      binding: 'company.name',
      x: 354,
      y: 95,
      width: 280,
      height: 26,
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'right',
      letterSpacing: 0.3,
    },
    {
      id: 'company_address',
      type: 'field',
      binding: 'company.address',
      x: 354,
      y: 130,
      width: 280,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'right',
      lineHeight: 1.6,
    },
    {
      id: 'company_post',
      type: 'text',
      x: 354,
      y: 152,
      width: 280,
      height: 18,
      content: '',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'right',
    },
    {
      id: 'company_org',
      type: 'field',
      binding: 'company.org_number',
      x: 354,
      y: 174,
      width: 280,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'right',
    },
    {
      id: 'company_account',
      type: 'field',
      binding: 'company.account_number',
      x: 354,
      y: 196,
      width: 280,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'company_email',
      type: 'field',
      binding: 'company.contact_email',
      x: 354,
      y: 218,
      width: 280,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'right',
    },
    // Elegant divider
    {
      id: 'divider_1',
      type: 'shape',
      shapeType: 'rectangle',
      x: 80,
      y: 290,
      width: 554,
      height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0,
      zIndex: 0,
    },
    // Bill To section - refined styling
    {
      id: 'bill_to_label',
      type: 'text',
      x: 80,
      y: 320,
      width: 200,
      height: 12,
      content: 'Bill To',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 600,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    {
      id: 'customer_name',
      type: 'field',
      binding: 'customer.name',
      x: 80,
      y: 345,
      width: 400,
      height: 24,
      fontFamily: 'Inter',
      fontSize: 17,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.2,
    },
    {
      id: 'customer_address',
      type: 'field',
      binding: 'customer.address',
      x: 80,
      y: 375,
      width: 400,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      lineHeight: 1.6,
    },
    {
      id: 'customer_post',
      type: 'text',
      x: 80,
      y: 397,
      width: 400,
      height: 18,
      content: '',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    // Elegant divider before table
    {
      id: 'divider_2',
      type: 'shape',
      shapeType: 'rectangle',
      x: 80,
      y: 440,
      width: 554,
      height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0,
      zIndex: 0,
    },
    // Premium table with refined styling
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 80,
      y: 460,
      width: 554,
      height: 350,
      columns: [
        { header: 'Description', field: 'description', width: 280, align: 'left' },
        { header: 'Qty', field: 'quantity', width: 70, align: 'right' },
        { header: 'Unit Price', field: 'unit_price', width: 100, align: 'right' },
        { header: 'VAT', field: 'vat_rate', width: 50, align: 'right' },
        { header: 'Amount', field: 'line_total', width: 100, align: 'right' },
      ],
      rowHeight: 32,
      maxRows: 9,
      headerBackgroundColor: 'transparent',
      headerTextColor: '#0d3e51',
      headerFontSize: 10,
      headerFontWeight: 700,
      headerTextTransform: 'uppercase',
      headerLetterSpacing: 1.5,
      backgroundColor: 'transparent',
      rowTextColor: '#0d3e51',
      borderRadius: 0,
      borderColor: '#e8f0ef',
      borderWidth: 1,
      alternateRowColor: '#fafbfb',
    },
    // Elegant summary section
    {
      id: 'summary_container',
      type: 'shape',
      shapeType: 'rectangle',
      x: 384,
      y: 830,
      width: 250,
      height: 160,
      backgroundColor: '#f8faf9',
      borderWidth: 1,
      borderColor: '#e8f0ef',
      borderRadius: 0,
      zIndex: 0,
    },
    {
      id: 'subtotal_label',
      type: 'text',
      x: 394,
      y: 850,
      width: 150,
      height: 20,
      content: 'Subtotal',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    {
      id: 'subtotal',
      type: 'field',
      binding: 'invoice.subtotal',
      x: 544,
      y: 850,
      width: 80,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'vat_label',
      type: 'text',
      x: 394,
      y: 880,
      width: 150,
      height: 20,
      content: 'VAT',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    {
      id: 'vat_total',
      type: 'field',
      binding: 'invoice.vat_total',
      x: 544,
      y: 880,
      width: 80,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'divider_3',
      type: 'shape',
      shapeType: 'rectangle',
      x: 394,
      y: 920,
      width: 230,
      height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0,
      zIndex: 1,
    },
    {
      id: 'total_label',
      type: 'text',
      x: 394,
      y: 940,
      width: 150,
      height: 28,
      content: 'Total Amount',
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    {
      id: 'total',
      type: 'field',
      binding: 'invoice.total',
      x: 544,
      y: 940,
      width: 80,
      height: 28,
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'right',
      letterSpacing: 0.3,
    },
    // Bottom accent bar
    {
      id: 'bottom_accent',
      type: 'shape',
      shapeType: 'rectangle',
      x: 80,
      y: 1020,
      width: 554,
      height: 3,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      borderRadius: 0,
      zIndex: 0,
    },
  ],
};

