/**
 * Modern Pro Premium Template
 * Contemporary design with strong visual hierarchy, modern layout patterns, and bold typography
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'premium_modern_pro',
    name: 'Modern Pro',
    description: 'Contemporary design with strong visual hierarchy, modern layout patterns, and bold typography',
    version: '1.0.0',
    premium: true,
    tags: ['modern', 'bold', 'premium', 'norsk'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: {
      top: 45,
      left: 55,
      right: 55,
      bottom: 45,
    },
    background: null,
  },
  elements: [
    // Bold header section with gradient-like effect
    {
      id: 'header_background',
      type: 'shape',
      shapeType: 'rectangle',
      x: 55,
      y: 45,
      width: 684,
      height: 140,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      borderRadius: 0,
      zIndex: 0,
    },
    // Invoice title - bold and modern
    {
      id: 'title',
      type: 'text',
      x: 75,
      y: 65,
      width: 400,
      height: 55,
      content: 'INVOICE',
      fontFamily: 'Inter',
      fontSize: 64,
      fontWeight: 900,
      color: '#ffffff',
      align: 'left',
      letterSpacing: 4,
    },
    // Invoice details in header
    {
      id: 'invoice_number',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 75,
      y: 130,
      width: 300,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 500,
      color: '#ffffff',
      align: 'left',
      opacity: 0.95,
    },
    {
      id: 'invoice_date',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 385,
      y: 130,
      width: 200,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 500,
      color: '#ffffff',
      align: 'left',
      opacity: 0.95,
    },
    // Company info overlay on header
    {
      id: 'company_name',
      type: 'field',
      binding: 'company.name',
      x: 439,
      y: 65,
      width: 300,
      height: 24,
      fontFamily: 'Inter',
      fontSize: 17,
      fontWeight: 700,
      color: '#ffffff',
      align: 'right',
    },
    {
      id: 'company_address',
      type: 'field',
      binding: 'company.address',
      x: 439,
      y: 95,
      width: 300,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#ffffff',
      align: 'right',
      opacity: 0.9,
    },
    {
      id: 'company_org',
      type: 'field',
      binding: 'company.org_number',
      x: 439,
      y: 117,
      width: 300,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#ffffff',
      align: 'right',
      opacity: 0.9,
    },
    {
      id: 'company_account',
      type: 'field',
      binding: 'company.account_number',
      x: 439,
      y: 139,
      width: 300,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 600,
      color: '#ffffff',
      align: 'right',
    },
    // Content section with modern spacing
    {
      id: 'bill_to_section',
      type: 'text',
      x: 55,
      y: 220,
      width: 300,
      height: 14,
      content: 'BILL TO',
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 700,
      color: '#6e8b97',
      align: 'left',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    {
      id: 'customer_name',
      type: 'field',
      binding: 'customer.name',
      x: 55,
      y: 245,
      width: 350,
      height: 26,
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'customer_address',
      type: 'field',
      binding: 'customer.address',
      x: 55,
      y: 278,
      width: 350,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'customer_post',
      type: 'text',
      x: 55,
      y: 300,
      width: 350,
      height: 18,
      content: '',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    // Modern table with strong styling
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 55,
      y: 350,
      width: 684,
      height: 420,
      columns: [
        { header: 'ITEM', field: 'description', width: 380, align: 'left' },
        { header: 'QTY', field: 'quantity', width: 70, align: 'right' },
        { header: 'PRICE', field: 'unit_price', width: 110, align: 'right' },
        { header: 'VAT', field: 'vat_rate', width: 60, align: 'right' },
        { header: 'TOTAL', field: 'line_total', width: 110, align: 'right' },
      ],
      rowHeight: 32,
      maxRows: 11,
      headerBackgroundColor: '#0d3e51',
      headerTextColor: '#ffffff',
      headerFontSize: 11,
      headerFontWeight: 700,
      headerTextTransform: 'uppercase',
      headerLetterSpacing: 1.5,
      backgroundColor: '#ffffff',
      rowTextColor: '#0d3e51',
      borderRadius: 0,
      borderColor: '#d5e7e6',
      borderWidth: 1,
      alternateRowColor: '#f8faf9',
    },
    // Summary section with accent
    {
      id: 'summary_accent',
      type: 'shape',
      shapeType: 'rectangle',
      x: 434,
      y: 790,
      width: 305,
      height: 5,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      zIndex: 0,
    },
    {
      id: 'subtotal_label',
      type: 'text',
      x: 444,
      y: 815,
      width: 200,
      height: 20,
      content: 'Subtotal',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.5,
    },
    {
      id: 'subtotal',
      type: 'field',
      binding: 'invoice.subtotal',
      x: 644,
      y: 815,
      width: 95,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'vat_label',
      type: 'text',
      x: 444,
      y: 845,
      width: 200,
      height: 20,
      content: 'VAT',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 0.5,
    },
    {
      id: 'vat_total',
      type: 'field',
      binding: 'invoice.vat_total',
      x: 644,
      y: 845,
      width: 95,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'divider',
      type: 'shape',
      shapeType: 'rectangle',
      x: 444,
      y: 880,
      width: 295,
      height: 2,
      backgroundColor: '#0d3e51',
      borderWidth: 0,
      zIndex: 1,
    },
    {
      id: 'total_label',
      type: 'text',
      x: 444,
      y: 900,
      width: 200,
      height: 32,
      content: 'TOTAL',
      fontFamily: 'Inter',
      fontSize: 22,
      fontWeight: 900,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 2,
    },
    {
      id: 'total',
      type: 'field',
      binding: 'invoice.total',
      x: 644,
      y: 900,
      width: 95,
      height: 32,
      fontFamily: 'Inter',
      fontSize: 22,
      fontWeight: 900,
      color: '#0d3e51',
      align: 'right',
      letterSpacing: 0.5,
    },
  ],
};

