/**
 * Modern Minimal Template
 * Clean and spacious design with modern typography
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'preset_modern_minimal',
    name: 'Modern Minimal',
    description: 'Clean and spacious design with modern typography',
    version: '1.0.0',
    premium: false,
    tags: ['minimal', 'modern', 'norsk'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: {
      top: 60,
      left: 60,
      right: 60,
      bottom: 60,
    },
    background: null,
  },
  elements: [
    {
      id: 'title',
      type: 'text',
      x: 60,
      y: 60,
      width: 200,
      height: 50,
      content: 'FAKTURA',
      fontFamily: 'Inter',
      fontSize: 36,
      fontWeight: 300,
      color: '#0d3e51',
      align: 'left',
      letterSpacing: 2,
    },
    {
      id: 'invoice_number_label',
      type: 'text',
      x: 60,
      y: 140,
      width: 120,
      height: 16,
      content: 'Fakturanummer:',
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    {
      id: 'invoice_number',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 190,
      y: 140,
      width: 150,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'invoice_date_label',
      type: 'text',
      x: 60,
      y: 165,
      width: 120,
      height: 16,
      content: 'Dato:',
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    {
      id: 'invoice_date',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 190,
      y: 165,
      width: 150,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'company_name',
      type: 'field',
      binding: 'company.name',
      x: 60,
      y: 220,
      width: 300,
      height: 24,
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'company_address',
      type: 'field',
      binding: 'company.address',
      x: 60,
      y: 250,
      width: 300,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'company_post_number',
      type: 'field',
      binding: 'company.post_number',
      x: 60,
      y: 270,
      width: 100,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'company_post_location',
      type: 'field',
      binding: 'company.post_location',
      x: 170,
      y: 270,
      width: 190,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'customer_label',
      type: 'text',
      x: 450,
      y: 220,
      width: 200,
      height: 16,
      content: 'Til:',
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    {
      id: 'customer_name',
      type: 'field',
      binding: 'customer.name',
      x: 450,
      y: 245,
      width: 250,
      height: 20,
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
    },
    {
      id: 'customer_address',
      type: 'field',
      binding: 'customer.address',
      x: 450,
      y: 270,
      width: 250,
      height: 16,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
    },
    {
      id: 'divider',
      type: 'text',
      x: 60,
      y: 320,
      width: 640,
      height: 1,
      content: '',
      backgroundColor: '#d5e7e6',
      fontFamily: 'Inter',
      fontSize: 1,
      fontWeight: 400,
      color: '#d5e7e6',
      align: 'left',
    },
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 60,
      y: 350,
      width: 640,
      height: 400,
      columns: [
        { header: 'Beskrivelse', field: 'description', width: 350, align: 'left' },
        { header: 'Antall', field: 'quantity', width: 70, align: 'right' },
        { header: 'Pris', field: 'unit_price', width: 100, align: 'right' },
        { header: 'MVA', field: 'vat_rate', width: 60, align: 'right' },
        { header: 'Total', field: 'line_total', width: 100, align: 'right' },
      ],
      rowHeight: 24,
      maxRows: 12,
      headerBackgroundColor: '#f0f8f5',
      headerTextColor: '#0d3e51',
      backgroundColor: 'transparent',
      rowTextColor: '#0d3e51',
      borderRadius: 0,
    },
    {
      id: 'subtotal_label',
      type: 'text',
      x: 500,
      y: 780,
      width: 100,
      height: 18,
      content: 'Delsum:',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 500,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'subtotal',
      type: 'field',
      binding: 'invoice.subtotal',
      x: 610,
      y: 780,
      width: 90,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'vat_label',
      type: 'text',
      x: 500,
      y: 810,
      width: 100,
      height: 18,
      content: 'MVA:',
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 500,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'vat_total',
      type: 'field',
      binding: 'invoice.vat_total',
      x: 610,
      y: 810,
      width: 90,
      height: 18,
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'total_label',
      type: 'text',
      x: 500,
      y: 850,
      width: 100,
      height: 24,
      content: 'Total:',
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'right',
    },
    {
      id: 'total',
      type: 'field',
      binding: 'invoice.total',
      x: 610,
      y: 850,
      width: 90,
      height: 24,
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'right',
    },
  ],
};

