/**
 * Nordisk Pro — Preset template
 * Clean Scandinavian design with structured header, green accents, and polished footer
 */
module.exports = {
  schemaVersion: 1,
  meta: {
    id: 'preset_nordisk_pro',
    name: 'Nordisk Pro',
    description: 'Ren og profesjonell mal med skandinavisk typografi og grønn aksent',
    version: '1.0.0',
    premium: false,
    tags: ['profesjonell', 'nordisk', 'norsk'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  page: {
    size: 'A4',
    margin: { top: 56, left: 56, right: 56, bottom: 56 },
    background: null,
  },
  elements: [

    // ── Top accent stripe ──────────────────────────────────────────────────────
    {
      id: 'stripe_top',
      type: 'shape',
      shapeType: 'rectangle',
      x: 0, y: 0, width: 794, height: 5,
      backgroundColor: '#2abd8a',
      borderWidth: 0, borderColor: 'transparent', borderStyle: 'solid', borderRadius: 0,
      zIndex: 0,
    },

    // ── Logo ──────────────────────────────────────────────────────────────────
    {
      id: 'logo',
      type: 'image',
      x: 56, y: 20,
      width: 140, height: 70,
      src: '',
      preserveAspectRatio: true,
      zIndex: 2,
    },

    // ── FAKTURA heading ───────────────────────────────────────────────────────
    {
      id: 'heading_faktura',
      type: 'text',
      x: 440, y: 22,
      width: 298, height: 52,
      content: 'FAKTURA',
      fontFamily: 'Inter',
      fontSize: 38,
      fontWeight: 200,
      color: '#0d3e51',
      align: 'right',
      letterSpacing: 4,
      zIndex: 1,
    },

    // ── Company name (header) ─────────────────────────────────────────────────
    {
      id: 'company_name_header',
      type: 'field',
      binding: 'company.name',
      x: 56, y: 102,
      width: 300, height: 22,
      fontFamily: 'Inter',
      fontSize: 15,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'company_address',
      type: 'field',
      binding: 'company.address',
      x: 56, y: 128,
      width: 300, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'company_post_number',
      type: 'field',
      binding: 'company.post_number',
      x: 56, y: 145,
      width: 55, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'company_post_location',
      type: 'field',
      binding: 'company.post_location',
      x: 116, y: 145,
      width: 240, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },

    // ── Invoice meta (right column) ───────────────────────────────────────────
    {
      id: 'meta_number_label',
      type: 'text',
      x: 454, y: 90,
      width: 140, height: 13,
      content: 'Fakturanummer',
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 600,
      color: '#6e8b97',
      align: 'right',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      zIndex: 1,
    },
    {
      id: 'meta_number_value',
      type: 'field',
      binding: 'invoice.invoice_number',
      x: 594, y: 90,
      width: 144, height: 13,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'meta_date_label',
      type: 'text',
      x: 454, y: 110,
      width: 140, height: 13,
      content: 'Fakturadato',
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'right',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      zIndex: 1,
    },
    {
      id: 'meta_date_value',
      type: 'field',
      binding: 'invoice.invoice_date',
      x: 594, y: 110,
      width: 144, height: 13,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'meta_due_label',
      type: 'text',
      x: 454, y: 130,
      width: 140, height: 13,
      content: 'Forfallsdato',
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'right',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      zIndex: 1,
    },
    {
      id: 'meta_due_value',
      type: 'field',
      binding: 'invoice.due_date',
      x: 594, y: 130,
      width: 144, height: 13,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },

    // ── Divider ───────────────────────────────────────────────────────────────
    {
      id: 'divider_header',
      type: 'shape',
      shapeType: 'rectangle',
      x: 56, y: 172,
      width: 682, height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0, borderColor: 'transparent', borderStyle: 'solid', borderRadius: 0,
      zIndex: 0,
    },

    // ── Customer address block ─────────────────────────────────────────────────
    {
      id: 'customer_section_label',
      type: 'text',
      x: 56, y: 184,
      width: 200, height: 12,
      content: 'Faktureres til',
      fontFamily: 'Inter',
      fontSize: 7.5,
      fontWeight: 600,
      color: '#2abd8a',
      align: 'left',
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      zIndex: 1,
    },
    {
      id: 'customer_name',
      type: 'field',
      binding: 'customer.name',
      x: 56, y: 200,
      width: 320, height: 21,
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'customer_address',
      type: 'field',
      binding: 'customer.address',
      x: 56, y: 225,
      width: 320, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'customer_post_number',
      type: 'field',
      binding: 'customer.post_number',
      x: 56, y: 241,
      width: 55, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'customer_post_location',
      type: 'field',
      binding: 'customer.post_location',
      x: 116, y: 241,
      width: 260, height: 14,
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'left',
      zIndex: 1,
    },
    {
      id: 'customer_org',
      type: 'field',
      binding: 'customer.org_number',
      x: 56, y: 257,
      width: 320, height: 13,
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 400,
      color: '#94a3b8',
      align: 'left',
      zIndex: 1,
    },

    // ── Items table ───────────────────────────────────────────────────────────
    {
      id: 'items_table',
      type: 'table',
      binding: 'invoice.items',
      x: 56, y: 294,
      width: 682, height: 478,
      columns: [
        { header: 'Beskrivelse',  field: 'description', width: 310, align: 'left'  },
        { header: 'Antall',       field: 'quantity',    width:  62, align: 'right' },
        { header: 'Enhetspris',   field: 'unit_price',  width: 100, align: 'right' },
        { header: 'MVA',          field: 'vat_rate',    width:  60, align: 'right' },
        { header: 'Beløp',        field: 'line_total',  width: 150, align: 'right' },
      ],
      rowHeight: 26,
      maxRows: 15,
      headerBackgroundColor: '#0d3e51',
      headerTextColor: '#ffffff',
      backgroundColor: 'transparent',
      rowTextColor: '#0d3e51',
      borderRadius: 0,
      zIndex: 1,
    },

    // ── Totals ────────────────────────────────────────────────────────────────
    {
      id: 'subtotal_label',
      type: 'text',
      x: 524, y: 792,
      width: 110, height: 17,
      content: 'Delsum',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'subtotal_value',
      type: 'field',
      binding: 'invoice.subtotal',
      x: 632, y: 792,
      width: 106, height: 17,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'vat_label',
      type: 'text',
      x: 524, y: 815,
      width: 110, height: 17,
      content: 'MVA',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'vat_value',
      type: 'field',
      binding: 'invoice.vat_total',
      x: 632, y: 815,
      width: 106, height: 17,
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },

    // Total divider line
    {
      id: 'total_divider',
      type: 'shape',
      shapeType: 'rectangle',
      x: 524, y: 840,
      width: 214, height: 1,
      backgroundColor: '#c2d8d5',
      borderWidth: 0, borderColor: 'transparent', borderStyle: 'solid', borderRadius: 0,
      zIndex: 1,
    },

    {
      id: 'total_label',
      type: 'text',
      x: 524, y: 850,
      width: 110, height: 24,
      content: 'Å betale',
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 700,
      color: '#0d3e51',
      align: 'right',
      zIndex: 1,
    },
    {
      id: 'total_value',
      type: 'field',
      binding: 'invoice.total',
      x: 632, y: 850,
      width: 106, height: 24,
      fontFamily: 'Inter',
      fontSize: 15,
      fontWeight: 700,
      color: '#1a7a54',
      align: 'right',
      zIndex: 1,
    },

    // ── Footer background ──────────────────────────────────────────────────────
    {
      id: 'footer_bg',
      type: 'shape',
      shapeType: 'rectangle',
      x: 0, y: 1056,
      width: 794, height: 67,
      backgroundColor: '#f5faf7',
      borderWidth: 0, borderColor: 'transparent', borderStyle: 'solid', borderRadius: 0,
      zIndex: 0,
    },
    {
      id: 'footer_border',
      type: 'shape',
      shapeType: 'rectangle',
      x: 0, y: 1056,
      width: 794, height: 1,
      backgroundColor: '#d5e7e6',
      borderWidth: 0, borderColor: 'transparent', borderStyle: 'solid', borderRadius: 0,
      zIndex: 1,
    },

    // Footer — bank account
    {
      id: 'footer_bank_label',
      type: 'text',
      x: 56, y: 1072,
      width: 80, height: 13,
      content: 'Kontonr.',
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      zIndex: 2,
    },
    {
      id: 'footer_bank_value',
      type: 'field',
      binding: 'company.account_number',
      x: 136, y: 1072,
      width: 160, height: 13,
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      zIndex: 2,
    },

    // Footer — org number
    {
      id: 'footer_org_label',
      type: 'text',
      x: 320, y: 1072,
      width: 52, height: 13,
      content: 'Org.nr.',
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      zIndex: 2,
    },
    {
      id: 'footer_org_value',
      type: 'field',
      binding: 'company.org_number',
      x: 372, y: 1072,
      width: 160, height: 13,
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 400,
      color: '#0d3e51',
      align: 'left',
      zIndex: 2,
    },

    // Footer — email (right-aligned)
    {
      id: 'footer_email',
      type: 'field',
      binding: 'company.contact_email',
      x: 556, y: 1072,
      width: 182, height: 13,
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 400,
      color: '#6e8b97',
      align: 'right',
      zIndex: 2,
    },

    // Footer — due date reminder
    {
      id: 'footer_due_label',
      type: 'text',
      x: 56, y: 1090,
      width: 100, height: 13,
      content: 'Forfallsdato',
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'left',
      zIndex: 2,
    },
    {
      id: 'footer_due_value',
      type: 'field',
      binding: 'invoice.due_date',
      x: 156, y: 1090,
      width: 140, height: 13,
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 600,
      color: '#0d3e51',
      align: 'left',
      zIndex: 2,
    },

    // Footer — company name (right-aligned)
    {
      id: 'footer_company_name',
      type: 'field',
      binding: 'company.name',
      x: 556, y: 1090,
      width: 182, height: 13,
      fontFamily: 'Inter',
      fontSize: 8.5,
      fontWeight: 500,
      color: '#6e8b97',
      align: 'right',
      zIndex: 2,
    },
  ],
};
